# Generated by Django 2.1.2 on 2018-10-31 23:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('celery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('result_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('result_str', models.TextField(default='No result available')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
