version: '3.6'

networks:
  mynet:
    driver: overlay
    driver_opts:
      encrypted: "true"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - mynet
  redis:
    image: redis:latest
    networks:
      - mynet
  web:
    build: .
    command: python /code/manage.py migrate --noinput
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db
      - redis
    networks:
      - mynet
  celery:
    build: .
    command: celery worker -A proteinPrimes -l info
    volumes:
      - .:/code
    networks:
      - mynet
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
